version: '3.7'

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/myfolder/src
        ports:
            - 3000:3000

    my-database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'mydocker02'
            MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - 3306:3306
